### ISSUE TITLE
Constantly 'Train can't find it's way to destination' (automatically gone after +-10 seconds)

### ISSUE THREAD

**Issue by DikkePannekoek** [voxeltycoon/bug-tracker#115]
Hi,

I'm getting the 'Train [number] can't find it's way to destination' message for multiple trains. Sometimes it's instantly solved (less than a second), however sometimes the train just stands still, waits for max 10 seconds with the warning sign and then starts moving again to its destination.

Do you know what is the issue? I've attached a link to my savegame, so you can observe it.

[https://drive.google.com/file/d/1wdf--ahz8QIH90b_Y-qucraxedPheMd6/view?usp=sharing](url)

Hope you can help.

Cheers!

**Comment by DikkePannekoek** [comment]
What I just observed, is that it could be related to a station being full at the moment that a train tries to travel there. I saw a 4 track station having 4 trains parked simultaneously. The train trying to travel there then said it could not find it's way to the destination. (not sure if this is causing it).

**Comment by katepolak** [comment]
It shouldn't, I will take a look at the save file when I can.

**Comment by lostwizard** [comment]
I had something similar happening with trucks in one game. Trucks at one particular station would almost always pop up with "I'm lost" but then a short time later start running and make it to their destination. Alas, I can't find a save for it - seems like it didn't occur to me to save the game while the problem was happening and I just removed the problem route. My suspicion based on observing how trucks run on roads in a different gam is that there is some sort of congestion avoidance behaviour in the pathfinding, or something is not being considered as passable due to a truck being present (tunnel or drive through station maybe?). Trucks don't always take the same route, and sometimes take a longer route than normal.

**Comment by victorleblais** [comment]
Hi !
I also have the same issue and it happens extremely frequently in my save game.

I had the same assumption as @DikkePannekoek but I've had plenty of instances where the destination's station had free spots.

Here's my save game: https://drive.google.com/open?id=1-pXczuDscVmKd06-YNwcqeIIV7A2wwY5
Here's the list of mods I use:
- Modern House by vncnt
- More Houses by KingPengu
- buildings by meinroman
- Modern Supermarket by vncnt
- TCL Searchlight Signal Pack by TransCanadaLimited (thumbnail says "outdated")
- TCL Searchlight Signals by TransCanadaLimited

Here's a zip of the mods in case they're not available or whatever: https://drive.google.com/open?id=1AM6o4VvNZg1hY7VEISRKmFXmAjM1lcbt

I have also made a video where I look at the trains having issue and follow them when they find their path again: https://youtu.be/utCuQfQCS9I

A bit unrelated to that issue but still related to pathfinding: I've noticed trains make big detours to avoid the shortest route when there's a train in front of them (like, instead of staying behind that train they "prefer" to make a 30s detour).

**Comment by lostwizard** [comment]
I have two save games that may help with the lost/unlost/lost sequence. These are:

https://www.l-w.ca/losttruck.zip
https://www.l-w.ca/megalopolis.zip

(Links because the files are too big to upload here.)

The first one (losttruck) has a stone delivery at Tempe Halt (beside the lake) which regularly, but intermittently, ends up being lost, but then eventually starts running again.

The second one has several trucks that do the same but less regularly. It seems to be related to traffic density since it doesn't happen until there are quite a few trucks running around the map. Sometimes, forcing a route through another station in the middle seems to help, but not always.

I included both games in case having a couple of games with large truck fleets is helpful.

**Comment by voxeltycoon** [comment]
Fixed in 0.75
