### ISSUE TITLE
World creation impossible while deleted localisation file found in 'settings.json'

### ISSUE THREAD

**Issue by SlightlyAmazing** [voxeltycoon/bug-tracker#198]
**Describe the bug**
When loading deleted localisations from 'settings.json' it causes a bug and means you can't start a new world.

**Steps to reproduce**
1. add new '.names' file
2. use it to create game, or otherwise set it to default in 'settings.json'
3. delete new '.names' file
4. try to create new world. It won't work.

**Build version**
0.85 steam EA

**Platform**
Windows 10 (plus I would Imagen it universal)

**Reproducibility**
every time

**Logs/saves**
[Player.log](https://github.com/voxeltycoon/bug-tracker/files/6323932/Player.log)

**Comment by victorleblais** [comment]
Isn't that normal? It sounds like you're trying to use stuff that no longer exist.

**Comment by SlightlyAmazing** [comment]
You could argue that. However, I think if the game automatically sets a reference to a file which you then delete, it shouldn’t cause an error

**Comment by katepolak** [comment]
I could see this being both the correct behaviour because you wouldn't want your localisation changing suddenly if some happened, that would be hard to figure out for the average player. But going back to a default one would likely also be a valid way to "solve" it. This is something for the devs to decide, so for now I will mark this as "not a bug" but will leave the issue opened for further discussion.

**Comment by andrewpey** [comment]
It's not a bug indeed since the modding of locales is not yet supported.

It will be supported in the future, however. We'll ensure that the game properly falls back in case a modded locale is no longer available.
