### ISSUE TITLE
Trains stop at every signal. In spite of a green light!

### ISSUE THREAD

**Issue by Carlos197833** [voxeltycoon/bug-tracker#219]
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots or video to help explain your problem.

**Steps to reproduce**
Steps to reproduce the behavior.

**Build version**
Version information can be found at the bottom of the settings window.

**Platform**
0.85.0.24.steam
Windows 10   

**Reproducibility**
How often an issue reproduces: every time, often, rare, once.

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/bug-tracker/blob/master/README.md#logs) if applicable.

**Comment by victorleblais** [comment]
Can you share your save file so we can take a look at that?

To do that, go into the "load save" menu and click the three dots then "share". It will open a window with a .zip file, simply drag and drop it in the comment input here.

**Comment by Carlos197833** [comment]
Unfortunately the file is to large!? The save file is 29 MB in size.

**Comment by Carlos197833** [comment]
![image](https://user-images.githubusercontent.com/82762424/115148463-010f0c00-a060-11eb-9746-82624da37244.png)

**Comment by victorleblais** [comment]
You can use free services like Google Drive, Dropbox or Wetransfer (that one doesn't require an account) to upload file and get a link to share !

**Comment by Carlos197833** [comment]
https://drive.google.com/file/d/1yCm7dIDDUgDjeNmkRf0sUjr4uxyorp5-/view?usp=sharing

https://drive.google.com/file/d/1yCm7dIDDUgDjeNmkRf0sUjr4uxyorp5-/view?usp=sharing

**Comment by Carlos197833** [comment]
I´ve launched a new game and the signal system works properly til now.

**Comment by victorleblais** [comment]
Your train stops because it cannot find a valid path to its destination.

You have made mistakes when signalling. All your stations suffer from the same issue: your stations cannot be entered from any side:
![image](https://user-images.githubusercontent.com/4365075/115150452-c198ed80-a068-11eb-88e1-696c7f7e11c3.png)

Keep in mind that signals are, by default, one-way only: you can't pass them from their back side unless another signal has been place on the same tile (visible by the two arrow indicators being grouped together).

Also, whenever possible, try to keep stuff going in one direction only, it'll make your life easier. For example, on your "loops", there's no reason to make them two-way. Here's a simple fix:
![image](https://user-images.githubusercontent.com/4365075/115150521-0cb30080-a069-11eb-8599-c4c99c4268b2.png)


And here are how the other places can be reworked:
![20210418171601_1](https://user-images.githubusercontent.com/4365075/115150706-d7f37900-a069-11eb-83b6-40963119f11a.jpg)
![20210418171609_1](https://user-images.githubusercontent.com/4365075/115150707-d88c0f80-a069-11eb-830d-030c9f8cd988.jpg)


Also, unrelated to your signalling issue, you have a train too long for its platform. Keep in mind this will make the loading/unloading inefficient.
![image](https://user-images.githubusercontent.com/4365075/115150740-ff4a4600-a069-11eb-9326-14b39acd4f99.png)

**Comment by Carlos197833** [comment]
Thanks a lot Sir! I´ll will try to follow your Advice.
