### ISSUE TITLE
Goods not accepted if not delivered by car

### ISSUE THREAD

**Issue by TristanGah** [voxeltycoon/bug-tracker#246]
**Describe the bug**
I have a warehouse with iron and coal which delivers to a smelter by conveyer to make iron bars. The smelter output is delivered by conveyer to a warehouse within reach of a fatory that needs iron bars but the factory won't take them. This second warehouse also has a truck station. Both this warehouse and truck station are within reach of the factory. If I deliver the goods by car to that warehouse, the factory will take them, but only the goods that got into the warehouse by car, not those who came by conveyor. The same problem occurs with trains instead of conveyers.

**Steps to reproduce**
Rebuild what I described. 
![Screenshot 2021-04-25 205752](https://user-images.githubusercontent.com/12159787/116005830-f7117e00-a608-11eb-98b5-7e875ecf0d9a.png)

**Build version**
0.85.1

**Platform**

Win 10

**Reproducibility**
everytime

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/bug-tracker/blob/master/README.md#logs) if applicable.

**Comment by asiaclonk** [comment]
You are misunderstanding something:
When a truck unloads cargo at a freight station, the station will directly deliver it to whatever is connected to it via the logistics tab of its properties. In your case the cargo is being divided 50/50 to the warehouse (if there is any space) and the industrial building. **Customers can at this point not accept items via anything other than vehicles unloading at stations.** Your truck was likely delivering all of its cargo to the industrial building via the freight station, because your warehouse is full.

If you have a freight station in range of a warehouse and a customer and set the freight station **to NOT output to the warehouse** (set it in the logistics tab), you can set the truck to load and immediately unload cargo, so that it takes it from the warehouse and deliver it to the customer in the same station.

One more thing:
Each customer building **has its own storage capacity**. Warehouses you build nearby are completely unrelated to it. When delivering to a freight station, the cargo is delivered to the customer storage first. Each in-game day, the customer will move a certain amount of storage items to its satisfied demand (based on its level). If there are no items in its storage on any day, your demand satisfaction rating decreases for that customer.

**Comment by SparxTheDragon** [comment]
i had this same issue,

i figured out the truck hack to make it work before coming here,  but it really seems strange that you cannot somehow manufacture and sell out of the same station 

by the description above, i understand that it is not a thing now,  but it would make sense if a station could sell to a customer directly, instead of a truck loading and unloading, but taking up the road space

in my game the iron bar customer was right next to a coal mine, so the gap in-between is the factory, it is frustrating that i then have to spend more money on logistics that literally doesn't go anywhere, and blocks access to trucks if i want to sell/ship these iron bars somewhere else....

**Comment by TristanGah** [comment]
Ok I guess this solves the issue. For now we have to deal with the workaround. Thanks for your responses and I hope this will get "fixed" soon.
